### ISSUE TITLE
Class or Interface Not Found

### ISSUE THREAD

**Issue by Sushil2526** [progress/Spark-Toolkit-Demos#1]
Hi,

I am getting below error on compliling DataObjectHandler.cls:
"Could not find class or interface OpenEdge.Core.SemanticVersion. (12886)".

I checked, but did not found some of the classes/interfaces (DataObjectError,SemanticVersion, DataObjectService, ServiceDiscoveryEventArgs ) in OpenEdge libraries.

These issues are coming in all the projects folder "\Spark-Toolkit-Demos\oe117".

Please suggest me on this issue.

**Comment by DustinGrau-PSC** [comment]
What version of OE are you using? It would be helpful to understand what your environment looks like. I can tell you that the minimum version should be at least 11.7.2, with 11.7.3 highly recommended.

**Comment by Sushil2526** [comment]
Thanks @DustinGrau-PSC .

I am using OE 11.7.0. I was migrating PMFO and it is compatible with OE 11.7. So, this made me impression that this tool has same compatibility.

**Comment by DustinGrau-PSC** [comment]
The demos are clearly listed as 11.7 to avoid the immediate confusion that they may be deployable on an 11.6 environment. However, I now realize the supplied README here does not fully explain that 11.7.2 is the ideal starting point for the provided release. The reason being that 11.7.0 is now well over a year old and there have been significant fixes and enhancements in SP1, SP2 in particular, and ideally SP3. I'll be fixing the omission regarding the recommended service pack in a future update.
