### ISSUE TITLE
UI setup

### ISSUE THREAD

**Issue by Sushil2526** [progress/Spark-Toolkit-Demos#2]
Hi,

I have successfully launched the services on the server. But I am stuck to making the UI from this project. Is this demo project contains code to launch services only?
I can not find the UI setup wizard on this project.

Please suggest.

**Comment by DustinGrau-PSC** [comment]
The demo project is currently just that. We do not yet have any of the related wizard/tooling available just yet on GitHub as the documentation has not been updated completely.

**Comment by Sushil2526** [comment]
Thank you for the information.

Is there any expected date by which the wizard/tooling will be available on GitHub? 
It would be very helpful for me.

**Comment by DustinGrau-PSC** [comment]
I don't have a timeline on that at present. It would be suggested that you look into the KUIB tooling as that is the supported product for building a UI against the business entities exposed.

**Comment by Sushil2526** [comment]
Thanks.

Are you referring to use below KUIB project available on GitHub, with current Spark-Toolkit-Demos project for integration to UI? 
https://github.com/progress/kendo-ui-builder-samples

If not then please provide the link of KUIB tooling.

**Comment by DustinGrau-PSC** [comment]
This is the product in question:
https://www.progress.com/openedge/components/kendo-ui-builder

The Spark-Toolkit-Demos are currently just for illustration of a self-contained application using the server-side toolkit. If you wish to build an application it is encouraged that you use one of the tools build for that purpose (KUIB).
